class RetryableException(Exception):
    pass


class NonRetryableException(Exception):
    pass
